# Generated by Django 5.1.7 on 2025-03-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Kalamazoo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='Michigan', max_length=100),
            preserve_default=False,
        ),
    ]
