# Generated by Django 5.1.7 on 2025-03-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_skill_mentee_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='skills_teach',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_mentee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.skill'),
        ),
        migrations.DeleteModel(
            name='Mentee',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
