# Generated by Django 5.1.7 on 2025-03-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
